version: '3.9'
services:
  db:
    image: postgres
    volumes:
    - db_data:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: postgres
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5432:5432"
    networks:
      - webapp
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
    - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    links:
      - "db:psql-server"
  frontend:
    image: node
    command: npm start dev
    volumes:
     - ./blog-frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
     - "3000:3000"
    networks:
      - webapp

  backend:
    image: node
    command: npm run start:dev
    volumes:
    - ./blog-backend:/usr/src/app
    working_dir: /usr/src/app
    ports:
    - "5000:5000"
    depends_on:
      - db
    environment:
     - CHOKIDAR_USEPOLLING=true
    networks:
    - webapp
volumes:
  db_data: {}
  pgadmin: {}
networks:
  webapp:
    driver: bridge